Add BypassCNandLan.rule
FQrabbit/SSTap-Rule pull request #542
Opened 2023-06-24 11:29 UTC by KoinuDayo

添加绕过大陆规则和一个cmd脚本用于更新规则
[上游URL](https://github.com/Hackl0us/GeoIP2-CN)
每三天在github actions自动构建并且推送到release

2023-06-24 15:14 UTC, NormanBB commented
可否添加 workflow? 这样我可以merge.
感谢您的贡献，it helps a lot.

2023-06-24 17:33 UTC, KoinuDayo commented
没用过github actions，照着上游的URL的workflow file写的。
~~应该可以用~~
就是里头有些东西可能得改改

2023-06-25 11:08 UTC, KoinuDayo commented
现在可以用了，只要在workflow file里加上 `user.name` 和在仓库里加上 `secret.GITHUB_TOKEN` 的量就行

2023-07-20 03:22 UTC, FQrabbit commented
git config user.email "``41898282+github-actions[bot]@users.noreply.github.com``"
git config user.name "``github-actions[bot]``"
请问这里的值是固定的吗，我也刚接触Actions

2023-07-20 03:25 UTC, FQrabbit requested changes
我也不太接触过Actions，如果能用Actions的名义commit的话那就更好了

2023-07-20 06:40 UTC, KoinuDayo commented
> 我也不太接触过Actions，如果能用Actions的名义commit的话那就更好了

https://github.com/community/community/discussions/26560#discussioncomment-3531273
在commit时使用这个就是以actions的名义commit了， https://github.com/KoinuDayo/warp-reg.sh 可以看我这个仓库的release branch，都是以actions的名义commit的。可以直接把我那部分的workflow文件里的git config复制粘贴过来，或者我修改好再合并。

2023-07-20 18:57 UTC, KoinuDayo commented
已经改好了，可以直接合
顺便修了个导致有空行的bug

2023-07-27 03:40 UTC, FQrabbit approved these changes

2023-07-27 10:37 UTC, merged